# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ca_simulator_pb2 as ca__simulator__pb2


class SimEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulationGif = channel.unary_unary(
                '/ca_simulator.SimEngine/RunSimulationGif',
                request_serializer=ca__simulator__pb2.SimRequest.SerializeToString,
                response_deserializer=ca__simulator__pb2.SimReply.FromString,
                )


class SimEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunSimulationGif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulationGif': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulationGif,
                    request_deserializer=ca__simulator__pb2.SimRequest.FromString,
                    response_serializer=ca__simulator__pb2.SimReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ca_simulator.SimEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunSimulationGif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ca_simulator.SimEngine/RunSimulationGif',
            ca__simulator__pb2.SimRequest.SerializeToString,
            ca__simulator__pb2.SimReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
